### ISSUE TITLE
Update project using android embedding  v2

### ISSUE THREAD

**Issue by zindlsn** [sabinbajracharya/fluttery-todo#10]
Migration steps:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

1. Update Andoridmanifest
2. Update MainActivity.java

**Comment by sabinbajracharya** [comment]
Hi @zindlsn, could you maybe send me a pull request?

**Comment by zindlsn** [comment]
I started your project with Flutter 20.10.1.  In this version also properties in TextTheme changed:
Before:
TextTheme(
          headline: TextStyle(fontSize: 32.0, fontWeight: FontWeight.w400),
          title: TextStyle(fontSize: 28.0, fontWeight: FontWeight.w500),
          body1: TextStyle(
          bodyText1: TextStyle(
            fontSize: 14.0,
            fontFamily: 'Hind',
          ),

After:
TextTheme(
          headline1: TextStyle(fontSize: 32.0, fontWeight: FontWeight.w400),
          subtitle1: TextStyle(fontSize: 28.0, fontWeight: FontWeight.w500),
          bodyText1: TextStyle(
            fontSize: 14.0,
            fontFamily: 'Hind',
          ),
        ),
I would also update that in the PR.
In addition I needed to update packages because of nullsafety
Please check first if my changes work for you

**Comment by sabinbajracharya** [comment]
@zindlsn  Thanks. Looks good! I have merged the changes.
