### ISSUE TITLE
Showing Wrong Day

### ISSUE THREAD

**Issue by trueshail** [sabinbajracharya/fluttery-todo#2]
-Shows Correct date and month but wrong day.

Current date time = 21 March Thursday

App Shows: - Sunday 21 Mar

**Comment by sabinbajracharya** [comment]
Thanks for the heads up! Ill have a look into it.

**Comment by trueshail** [comment]
Created a pull request.
Please check and verify.
Thanks. :)

**Comment by sabinbajracharya** [comment]
Thanks for the pull request!  Your pull request has been merged! Closed: #4 #5
