### ISSUE TITLE
Someone is selling your code for 18 USD on codecanyon

### ISSUE THREAD

**Issue by Shajeel-Afzal** [sabinbajracharya/fluttery-todo#6]
Hi, 

Very nice work! However, I wanna report that someone is selling your code for 18 USD on codecanyon!

Check it out here: https://codecanyon.net/item/mytodo-todo-list-flutter-app/24459786

**Comment by sabinbajracharya** [comment]
@Shajeel-Afzal Thanks for the heads up.
The fluttery-todo app is licensed under MIT which means:

You CAN:
    1) re-use the code freely for your own use,
    2) re-use the code freely for non-commercial AND commercial re-distribution, whether in source or binary form.

Let me know if you have any other questions!
