### ISSUE TITLE
migration to 2.2.2

### ISSUE THREAD

**Issue by digitpk** [sabinbajracharya/fluttery-todo#8]
Kindly helps me out in the migration of the application to the latest version i.e. 2.2.2

**Comment by digitpk** [comment]
or can you help me in updating the code to the latest version?

**Comment by sabinbajracharya** [comment]
Hi @digitpk! You want the project to support the latest dart version? If so, give me a couple of days and I will migrate the project to support the latest version.

**Comment by digitpk** [comment]
Thanks alot
I will be waiting for your response
@sabinbajracharya

**Comment by digitpk** [comment]
I am having trouble migrating to the model folder where you have defined the model of different tasks.

**Comment by sabinbajracharya** [comment]
I have merged #9 to master which migrates the project to null safety. Hope this helps.
